### ISSUE TITLE
Resign game has no confirm

### ISSUE THREAD

**Issue by steve-biggs** [cerisara/DragonGoApp#14]
I just accidentally hit the resign game button and it resigned me without a confirmation dialog. The absence of a confirmation in this context can clearly have significant consequences. Therefore, I think this probably constitutes a bug rather than a feature request. I am happy to help in fixing it but I might need a few pointers of where to look in the source code first.

**Comment by mzuther** [comment]
I can understand that you're annoyed because of what happened. But this is not the way to behave on GitHub. Cerisana has spent dozens (or hundreds) of hours coding an open source app you didn't have to pay for. Resigning without confirmation probably was an oversight, anyway.

I think it would be kind to re-phrase your bug report, just out of respect for the developer and his work.

Martin

**Comment by steve-biggs** [comment]
Apologies for my poorly worded bug report first time round. It was not meant as an insult to the developer. However, on re-reading it, I can see how it could be interpreted as such, so I am sorry if I caused any offence. What I was meaning to say was that I would like to contribute to the development of this excellent app but I might need some help getting started as I am not familiar with the code-base.

**Comment by mzuther** [comment]
Thanks! That's the spirit of GitHub... :)

**Comment by cerisara** [comment]
Thank you for this comment: it's now solved: I've just added a confirmation popup dialog before resigning.
It's not available on the F-droid repository, because I don't update it anymore, but you can download the latest apk from the webpage of the app http://cerisara.github.io/DragonGoApp/

**Comment by steve-biggs** [comment]
This is great. I finally had a chance to try this out and it works. Nice job. Thanks :)
