### ISSUE TITLE
Text is displayed instead of my game

### ISSUE THREAD

**Issue by andybalaam** [cerisara/DragonGoApp#9]
Some days the app just shows text instead of the game I am playing:

![screenshot_2016-10-03-19-08-23](https://cloud.githubusercontent.com/assets/76812/19054837/0d86e614-89b9-11e6-9a98-4227c5094a40.png)

**Comment by andybalaam** [comment]
In case it helps, the first few characters I see are:

    ( ;FF[4]GM[1] AP[DGS:1.19.12] PC

**Comment by cerisara** [comment]
Thanks for your feedback.
This issue just happens from time to time ?
What you see is the sgf file downloaded from DGS that *should* be rendered by Eidogo (in javascript in a WebView). My first guess would be that javascript may be disabled in your phone (because of some security settings), but if you do see the board from time to time, it's probably not the true reason...
What is your android version ?
May you try and track when does it show the board vs. when javascript fails to show the board ? (do you have other apps running in background ? what sequence of buttons did you press before ?)
Also, what happens when this happens, and you close the app + free the RAM, and start over the app ? Does it still fails or does it show the board correctly ?

**Comment by andybalaam** [comment]
Thanks for getting back to me.  It's a Samsung Galaxy S3 GT-I9300, Android verison 4.3, build number JSS15J.19300XXUGMK6

I'll try to do some research on the other questions.

**Comment by andybalaam** [comment]
Full sgf when it wasn't working:

```( ;FF[4]GM[1] AP[DGS:1.19.12] PC[Dragon Go Server: http://www.dragongoserver.net/] DT[2016-09-30,2016-10-04] GN[andybalaam-pablopicollo-1117909-20161004] SO[http://www.dragongoserver.net/game.php?gid=1117909] PB[pablo picollo (pablopicollo)] PW[Andy Balaam (andybalaam)] BR[13k] WR[12k] XM[11] GC[Game ID: 1117909 Game Type: GO (1:1) Rated: Y White Start Rating: 12k (-29%) - ELO 870 Black Start Rating: 13k (-37%) - ELO 762] OT[30 days with 1 day extra per move] RU[Japanese] SZ[9] KM[4.5] ;B[ee] C[pablo picollo (pablopicollo): have fun] ;W[cc] C[Andy Balaam (andybalaam): Enjoy the game!] ;B[dg] C[pablo picollo (pablopicollo): thx, have fun] ;W[fc] ;B[gf] ;W[ce] ;B[cf] ;W[be] ;B[gd] ;W[gc] ;B[bf] )```

**Comment by andybalaam** [comment]
When did a force stop and told Android to clear the app's cache it started working again, so I am happy!

**Comment by cerisara** [comment]
Hmm... Very strange: I've been using this app on a Samsung Y android 2.3 + a Wiko android 4.4 nearly every day since 3 years, and I never remember having seen that issue... Next time, just try to restart the app without resetting the cache, otherwise it's a real pain. And if it happens again, please let me know, I'd be interested to track this issue, because to be honest, I have no idea at all where it may come from...
I would need to be able to reproduce...

**Comment by andybalaam** [comment]
Thank you - I will let you know if it happens again. Brilliant app, I use it every day too!

**Comment by andybalaam** [comment]
It happened again!

![text-instead-of-game](https://cloud.githubusercontent.com/assets/76812/20136949/7d977e1e-a66f-11e6-88de-7f9679c4c00f.png)

I did a Force Stop and started it again, and it was the same again.

I can't skip game at the moment because I only have one game to play, but I will try that when I can.

**Comment by andybalaam** [comment]
```
$ curl -v http://www.dragongoserver.net/sgf.php?gid=1127537
*   Trying 193.44.211.51...
* Connected to www.dragongoserver.net (193.44.211.51) port 80 (#0)
> GET /sgf.php?gid=1127537 HTTP/1.1
> Host: www.dragongoserver.net
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Wed, 09 Nov 2016 11:34:32 GMT
< Server: Apache/2.2.15 (CentOS)
< X-Powered-By: PHP/5.3.3
< Content-Disposition: attachment; filename="JMonkey-andybalaam-1127537-20161109.sgf"
< Content-Description: PHP Generated Data
< Expires: Wed, 09 Nov 2016 11:39:32 GMT
< Last-Modified: Wed, 09 Nov 2016 11:34:32 GMT
< Content-Length: 633
< Connection: close
< Content-Type: application/x-go-sgf
< 
(
;FF[4]GM[1]
AP[DGS:1.19.12]
PC[Dragon Go Server: http://www.dragongoserver.net/]
DT[2016-11-08,2016-11-09]
GN[JMonkey-andybalaam-1127537-20161109]
SO[http://www.dragongoserver.net/game.php?gid=1127537]
EV[(Dragon Ladder) Tournament #1: DGS Ladder (9x9)]
RO[Round 1 of 1]
PB[Andy Balaam (andybalaam)]
PW[Jeff Miller (JMonkey)]
BR[12k]
WR[8k]
XM[2]
GC[Game ID: 1127537
Game Type: GO (1:1)
(Dragon Ladder) Tournament #1: DGS Ladder (9x9); with 311 participants
Rated: N

White Start Rating: 8k (+23%) - ELO 1322
Black Start Rating: 12k (-17%) - ELO 882]
OT[14 days with 1 day extra per move]
RU[Chinese]
SZ[9]
KM[7.0]
;B[cf]
;W[gg]
)
* Closing connection 0
```

**Comment by andybalaam** [comment]
I now have 2 games in my status.  When I skip the first, I see a text version of the second.

Let me know if I can give you any more information to help debug.

**Comment by cerisara** [comment]
Thanks for the feedback: do you know how to run "adb" from a computer with your smartphone connected in ?
If yes, then that would be of great help to send me the output of:
adb logcat
while running into this issue. Because that would display all the details about the error that is occurring...

So If I understand well, when you have 2 games, the first one is displayed correctly, but when you skip
the first game, the second game is shown with text ?

**Comment by cerisara** [comment]
Also, another idea, what happens when you press the "reset GUI" button ?

Same thing: what happens when you press the "redraw last goban" button ?

**Comment by andybalaam** [comment]
No, both games are displayed as text. I am an Android dev myself so I will try to get log output as soon as I get a chance

**Comment by cerisara** [comment]
I may have an idea: may be a sync issue btw threads and webview. Gonna try something...

**Comment by cerisara** [comment]
I think this solves the issue:
http://stackoverflow.com/questions/3306501/javascript-sometimes-doesnt-work-in-androids-webview
So if you're comfortable developing on Android, you may just add the following at the end of the file example.html which is somewhere on your sdcard (where DragonGoApp copies it actually):

>... other HTML ...
>
>    </body>
>    <script type="text/javascript">
>        document.querySelector("#checkItOut").addEventListener("touchstart", 
>            function() {
>                jsObject.performClick();
>        });
>    </script>
> </html>

But I'm right now completely rewriting the whole app to make it more robust... This will be v2; I expect it'll be done in a few months...

**Comment by andybalaam** [comment]
Sorry for the delay: today I finally go time to try this out.  I found that if I renamed the eidogo directory in Android/data/fx.xtof54.dragonGoApp then everything started working properly.  It has continued to work properly for me for several months, although initially I did this and it worked for a while, before going wrong again.

When I put it the original eidogo directory back, it stopped working again.

If I force stop Dragon Go App and connect adb, filtering on dragonGoApp, I get only this in the adb console:

```
12-18 07:54:44.685 2357-2808/? I/NotificationService: cancelToast pkg=fr.xtof54.dragonGoApp callback=android.app.ITransientNotification$Stub$Proxy@433fbd28
12-18 07:54:45.440 30461-30507/? I/System.out: debugloadurl file:///storage/emulated/0/Android/data/fr.xtof54.dragonGoApp/cache/eidogo/example.html
12-18 07:55:50.040 2357-2482/? I/WindowManager: Screenshot Window{4343a8d0 u0 fr.xtof54.dragonGoApp/fr.xtof54.jsgo.GoJsActivity} was all black! mSurfaceLayer=21025 minLayer=21025 maxLayer=21025
```

This doesn't look too useful to me.  Now I will try your suggestion from the previous comment.

**Comment by andybalaam** [comment]
Making the change you suggested to example.html did not work, even when I ensured the app was stopped, changed the file, and then restarted the app.

However, completely deleting the eidogo directory works for me, so I'm happy for now.

Thank you for a great app, and I look forward to v2!

**Comment by cerisara** [comment]
Thanks for your feedback ! OK, so the problem was not what I thought...
Here is the apk of the v2: http://talc1.loria.fr/users/cerisara/DragonGoAppv2.apk
(the old v1 is also here: http://talc1.loria.fr/users/cerisara/DragonGoApp.apk)

The code in v2 has been greatly simplified, support for OGS, forums and reviews is dropped (for now). Messages are not yet implemented. But normal playing is better coded. You also get the player names on top, the drop-down menu is simplified, you get a button for deleting the eidogo directory and recreating it. It should also be more stable. I hope your bug won't occur any more, thanks to a "lighter" code.

If you're OK to beta-test the v2, that'd be great !
I'm already using it everyday on my tablet, and it works fine for playing.
